fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    hosts: "git://github.com/alphagov/puppet-hosts.git"
    resolvconf: "git://github.com/alphagov/puppet-resolvconf.git"
    dnsmasq:
      repo: "git://github.com/alphagov/puppet-dnsmasq.git"
      ref: "origin/anchor_reload_and_resolvconf"
  symlinks:
    apache: "#{source_dir}"
